---
title: "git_00"
author: "Juliet Clark"
date: "5/23/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

How doth the little crocodile  
Improve his shining tail,  
And pour the waters of the Nile  
On every golden scale!  
How cheerfully he seems to grin  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Some say the world will end in fire,  
Some say in ice.  
From what I’ve tasted of desire  
I hold with those who favor fire.  
But if it had to perish twice,  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

“The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright--  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

The tulips are too excitable, it is winter here.    
Look how white everything is, how quiet, how snowed-in.  
I am learning peacefulness, lying by myself quietly  
As the light lies on these white walls, this bed, these hands.     
I am nobody; I have nothing to do with explosions.    
I have given my name and my day-clothes up to the nurses     
And my history to the anesthetist and my body to surgeons.  

They have propped my head between the pillow and the sheet-cuff     
Like an eye between two white lids that will not shut.  
Stupid pupil, it has to take everything in.  
The nurses pass and pass, they are no trouble,  
They pass the way gulls pass inland in their white caps,  
Doing things with their hands, one just the same as another,     
So it is impossible to tell how many there are.  

  
